# Generated by Django 5.2.11 on 2026-05-12 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cabinet_zone',
            field=models.CharField(choices=[('PROFILE_SETTINGS', 'PROFILE_SETTINGS'), ('CONTACT_LIST', 'CONTACT_LIST'), ('CHANGING_ZONE', 'CHANGING_ZONE'), ('STATISTICS', 'STATISTICS')], default='PROFILE_SETTINGS', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='view_mode',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=10),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rated_users',
            field=models.ManyToManyField(blank=True, related_name='rated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(default='LOGIN', max_length=30)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
