# Generated by Django 6.0.5 on 2026-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_paths',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_type',
            field=models.CharField(choices=[('ACCEPT_FRIEND', 'Принял в друзья'), ('SEND_MESSAGE', 'Отправил сообщение'), ('RATE', 'Поставил оценку'), ('ADD_IMG', 'Добавил фото'), ('REMOVE_IMG', 'Удалил фото'), ('LOGIN', 'Вошёл в систему'), ('REGISTER', 'Зарегистрировался'), ('LOGOUT', 'Вышел из системы'), ('REMOVE_FRIEND', 'Удалил из друзей'), ('DELETE_ACCOUNT', 'Удалил аккаунт'), ('PROFILE_VISIT', 'Посмотрел профиль'), ('FRIEND_REQUEST', 'Отправил заявку')], default='LOGIN', max_length=32),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cabinet_zone',
            field=models.CharField(default='main', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='view_mode',
            field=models.CharField(default='grid', max_length=32),
        ),
    ]
