# Generated by Django 6.0.5 on 2026-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateApp', '0002_user_url_paths_alter_logentry_log_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url_paths',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_type',
            field=models.CharField(default='LOGIN', max_length=30),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cabinet_zone',
            field=models.CharField(choices=[('PROFILE_SETTINGS', 'PROFILE_SETTINGS'), ('CONTACT_LIST', 'CONTACT_LIST'), ('CHANGING_ZONE', 'CHANGING_ZONE'), ('STATISTICS', 'STATISTICS')], default='PROFILE_SETTINGS', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='view_mode',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=10),
        ),
    ]
